urg_node:
  ros__parameters:
    serial_port: /dev/ttyACM0
    frame_id: laser
    calibrate_time: true
    serial_baud: 115200
    scan_skip: 0              #pomijanie skanów
    scan_time: 0.1            # czas skanowania (w sekundach)
    angle_min: -1.31          # -75° w radianach aby zignorować koło przed skanerem
    angle_max: 1.31           # 75° w radianach
    cluster: 1                # liczba skanów w klastrze
    intensity: true           # publikowanie intensywności
    publish_intensity: true   # publikowanie intensywności
    publish_multiecho: false  # publikowanie wielokrotnego echa
    time_offset: 0.0          # przesunięcie czasu (w sekundach) 
    skip: 0