slam_toolbox:
  ros__parameters:
    use_sim_time: false
    scan_topic: "/scan"
    mode: "mapping"
    map_file_name: "my_map"
    map_start_pose: [0.0, 0.0, 0.0]
    resolution: 0.05
    max_laser_range: 4.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.05
    use_scan_matching: true
    enable_interactive_mode: true
    publish_map_period: 1.0
    odom_frame: "laser"
    base_frame: "laser"
    scan_buffer_size: 10
    map_update_interval: 1.0
    map_frame: "map"
    throttle_scans: 1
    scan_queue_size: 1
